version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "7017:7017"
    environment:
      - BACKEND_PORT=7017
      - ALLOWED_ORIGINS=http://localhost:3006
      - DATABASE_URL=sqlite:///./feedback.db
      - LOG_LEVEL=INFO
    volumes:
      - ./backend/data:/app/data
      - ./backend/feedback.db:/app/feedback.db
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7017/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3006:3006"
    environment:
      - PORT=3006
      - NEXT_PUBLIC_API_URL=http://localhost:7017
    depends_on:
      backend:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3006"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  default:
    driver: bridge
